### ISSUE TITLE
Is Server Change for Everyone is officially shut down?

### ISSUE THREAD

**Issue by surya27895** [Decicus/discord-server-change#11]
I realize that only for everyone bot are not online but the another one does
is it officially shut down?

**Comment by Decicus** [comment]
Both have been shut down. The "Server changer for everyone" broke a while back for reasons I'm not 100% sure of, while the other was still "running" just not functioning.

Both bots have the same "issue", which is that the code hasn't been updated to work with Discord's changes to enforce slash commands. It's mostly my own fault, since I lacked the interest to maintain the project properly. I'll likely archive this code soon.

Either way, both bots should now be permanently offline. Feel free to kick both bots from your server, if you wish to get rid of them from your user list.
