### ISSUE TITLE
"allowEveryoneToMoveRegion" with Public Bot (Server Changer#1071) (Without Self-Hosting)

### ISSUE THREAD

**Issue by maarxx** [Decicus/discord-server-change#6]
Feature Request

Would it be possible to facilitate "allowEveryoneToMoveRegion" with Public Bot (Server Changer#1071) (Without Self-Hosting) ?

Maybe like a new command `!v allow-everyone on|off` and this command only responds to Owner / Administrator.

This would allow each server using the bot to set this feature without requiring self-hosting.

**Comment by Decicus** [comment]
I considered that during the initial implementation of the feature, but I decided against it because the bot currently doesn't do any permanent storage of settings (server-specific ones anyways).  

I still want to keep the bot simple as I'd rather not have to depend on a database server or anything of the like, so I'm not going to add a feature like this.  
Though maybe I'll just set up a separate bot instance for those that want `allowEveryoneToMoveRegion` to be set to `true`.

**Comment by Decicus** [comment]
Figured I'd update you about `allowEveryoneToMoveRegion` that I've set up the second bot that has this option enabled. Feel free to kick the first bot and inviting the second one: https://github.com/Decicus/discord-server-change#add-to-your-server

**Comment by maarxx** [comment]
@Decicus Thank you so much! Your bot is awesome! It's a big help.
